name: C++ CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.5'  

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Debug

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
