name: C++ CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x' 

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --target SortingTests 

    - name: List build directory
      run: |
        cd build
        ls -l

    - name: Run tests
      run: |
        cd build
        ctest -V --output-on-failure
